import { defineField, defineType } from 'sanity'

export const page = defineType({
  name: 'page',
  title: 'Sidor',
  type: 'document',
  groups: [
    { name: 'content', title: 'Innehåll', default: true },
    { name: 'header', title: 'Sidhuvud' },
    { name: 'seo', title: 'SEO' },
    { name: 'modal', title: 'Modal' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Titel',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      description: 'URL-vänlig identifierare för sidan. Genereras automatiskt från titeln. Används för att skapa sidans URL. Hem-sidan har en fast slug ("hem").',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 200,
      },
      group: 'content',
      validation: (Rule) => Rule.required(),
      readOnly: ({ parent }) => parent?.slug.current === 'hem',
    }),
    defineField({
      name: 'blocks',
      title: 'Sidkomponenter',
      description: 'Bygg upp sidan med olika komponenter (block). Dra och släpp för att ändra ordning.',
      type: 'array',
      group: 'content',
      of: [
        {type: 'block.text'},
        {type: 'block.image'},
        {type: 'block.video'},
        {type: 'block.politician'},
        {type: 'block.news'},
        {type: 'block.cta'},
        {type: 'block.stats'},
        {type: 'block.twoColumn'},
        {type: 'block.accordion'},
        {type: 'block.quote'},
        {type: 'block.imageGallery'},
        {type: 'block.contact'},
        {type: 'block.politicalAreas'},
        {type: 'block.geographicalAreas'},
      ],
    }),
    defineField({
      name: 'pageHeader',
      title: 'Sidhuvud',
      description: 'Rubrik, beskrivning, bild och valfri CTA-knapp som visas överst på sidan. Om inget anges visas sidans titel.',
      type: 'pageHeader',
      group: 'header',
    }),
    defineField({
      name: 'pageModal',
      title: 'Modal',
      description: 'Konfigurera en modal som visas automatiskt när sidan laddas. Användbart för viktiga meddelanden eller kampanjer.',
      type: 'pageModal',
      group: 'modal',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      description: 'Sökmotoroptimering. Ange titel, beskrivning, nyckelord och bild för bättre synlighet i sökmotorer.',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'pageHeader.description',
    },
  },
})
